DWD Overlays
codeforbielefeld/teuto-moisture-map-react pull request #4
Opened 2023-09-26 09:52 UTC by Preclur

Added DWD Overlays

2023-09-26 12:39 UTC, bnord01 requested changes

2023-09-26 12:39 UTC, bnord01 commented on src/App.tsx
> +                {/*<MoistureMarkers />*/}
Die hätten wir schon noch gerne. :)
```suggestion
                <MoistureMarkers />
```

2023-09-26 12:39 UTC, bnord01 commented on src/App.tsx
> +                </Marker>
Das kann wohl weg.

2023-09-26 12:39 UTC, bnord01 commented on src/App.tsx
> +                <VerticalSlider setValue={setValue} value={value} />
Hat noch keine Funktion, das ganze Feature würde ich in einem eigenen Pull Request sehen wollen, in dem es dann erst fertiggestellt werden kann, so dass wir dies hier vorher schon mergen können, sonst haben wir keinen sauberen Zustand.

2023-09-26 12:39 UTC, bnord01 commented on src/App.tsx
> +                />
Das ist etwas viel Detail für App Komponente, ich würde wie bei den MoistureMarkers eine eigene "Overlays" (o.ä.) Komponente vorschlagen, die das kapselt und hier nur eingebunden wird.

2023-09-26 12:39 UTC, bnord01 commented on src/App.tsx
> +            {/* <button onClick={test} /> */}
Das kann wohl weg.

2023-09-26 12:39 UTC, bnord01 commented on src/App.tsx
> +        <div className="App" style={{ zIndex: 1000 }}>
Die App hat schon eine Klasse. Der Style sollte besser in `App.css` ergänzt werden. Allerdings frage ich mich wozu der hier überhaupt gebraucht wird?

2023-09-26 12:39 UTC, bnord01 commented on src/App.tsx
> +    };
Das kann wohl weg.

2023-09-26 12:39 UTC, bnord01 commented on src/App.tsx
> +    });
Was tut das hier?

2023-09-26 12:39 UTC, bnord01 commented on src/App.tsx
> +    const [value, setValue] = useState<number>(0);
`value` ist ein sehr generischer Name, was tut der hier?

2023-09-26 12:39 UTC, bnord01 commented on src/components/CommandBar/ControlOverlay/index.tsx
> +*/
Das kann wohl weg?

2023-09-26 12:39 UTC, bnord01 commented on src/components/CommandBar/ControlOverlay/index.tsx
> +        <div>{show && <WMSOverlay layerName={layerName} attribution={attribution} setShowLayer={setShowLayer} />}</div>
Brauch es dieses `<div>` hier? Leeren Tag `<></>` verwenden?
```suggestion
        <>{show && <WMSOverlay layerName={layerName} attribution={attribution} setShowLayer={setShowLayer} />}</>
```

2023-09-26 12:39 UTC, bnord01 commented on src/components/SensorTooltip/index.tsx
> +                        <td>letzte</td>
Das sollte ja nur ein Test sein und das `<tr>` fehlt auch. Rückgängig machen.

2023-09-26 12:39 UTC, bnord01 commented on src/components/WMSOverlay/LegendOverlay/index.tsx
> +//import "./index.css";
Sollte das nicht importiert werden? Ansonsten kann die `index.css` wohl weg.

2023-09-26 12:39 UTC, bnord01 commented on src/components/WMSOverlay/LegendOverlay/index.tsx
> +                }}
Dem div einen className verpassen und den Style mit ins `index.css`.

2023-09-26 12:39 UTC, bnord01 commented on src/components/WMSOverlay/index.tsx
> +            </div>
Ich würde das ganze div hinter das `loading` packen damit es gar nicht erst im DOM hängt wenn nicht geladen wird.

2023-09-26 12:39 UTC, bnord01 commented on src/components/verticlSlider.tsx
Das kann wohl weg?

2023-09-26 12:39 UTC, bnord01 commented on src/components/verticalSlider.tsx
Wie in App.tsx angemerkt würde ich das in einem eigenen Pull Request sehen um erstmal dieses Feature abschließen zu können.

Was mir noch aufgefallen ist, wenn man den Slider benutzt verschiebt sich auch die Karte, das ist etwas komisch.

2023-09-26 12:39 UTC, bnord01 commented on src/hooks/useMoistureData.ts
> +            console.log(record.last_update);
Das sollte wohl weg.

2023-09-26 12:39 UTC, bnord01 commented on src/index.tsx
> +);
Das sollte wohl zurückgedreht werden, es produziert zumindest den folgenden Fehler in der Konsole:
`Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot`

2023-09-26 12:39 UTC, bnord01 commented on src/App.tsx
> +    setMap(map);
Das `useEffect` brauch es schon, sonst kommt es zu folgendem Fehler in der Konsole:
```
Warning: Cannot update a component (`App`) while rendering a different component (`MapHack`). To locate the bad setState() call inside `MapHack`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
MapHack@http://localhost:3000/static/js/bundle.js:60:17
div
MapContainerComponent@http://localhost:3000/static/js/bundle.js:117756:31
div
App@http://localhost:3000/static/js/bundle.js:74:76```

2024-06-10 07:21 UTC, micky-m commented
DWD Server ist sehr langsam in der Antwort, daher wird Lösung nicht übernommen aufgrund langer Ladezeiten.

2024-06-10 07:21 UTC, closed without merging